version: '3.8'

services:
  dashboard-mui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard-mui-app
    ports:
      - "5173:5173"
    volumes:
      # Montar o código fonte para hot reload durante desenvolvimento
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge

volumes:
  node_modules: